#spring.application.name=ticket-sales-service

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/hse_sc
    username: postgres-user
    password: postgres-password
    driver-class-name: org.postgresql.Driver

server:
  port: 8090