#spring.application.name=security.service

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/hse_sc
    username: postgres-user
    password: postgres-password
    driver-class-name: org.postgresql.Driver

  cloud:
    openfeign:
      client:
        config:
          ticket-sales-service:
            url: http://host.docker.internal:8090


logging:
  level:
    org:
      springframework:
        security: DEBUG
