#spring.application.name=security.service

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hse_sc
    username: postgres-user
    password: postgres-password
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework:
        security: DEBUG